### ISSUE TITLE
Choose development environment (Mac / Windows) displaying span elements instead of their content only

### ISSUE THREAD

**Issue by hrafil** [MicrosoftDocs/xamarin-docs.cs-cz#1]
Language mutation is czech.

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: ba4ac72b-0c09-80b8-7210-c77f1d2a6f42
* Version Independent ID: f39106cc-ec1f-55ea-002a-8928e742b551
* Content: [Hello, Android: Podrobné informace - Xamarin](https://docs.microsoft.com/cs-cz/xamarin/android/get-started/hello-android/hello-android-deepdive?pivots=windows)
* Content Source: [docs/android/get-started/hello-android/hello-android-deepdive.md](https://github.com/MicrosoftDocs/xamarin-docs.cs-CZ/blob/live/docs/android/get-started/hello-android/hello-android-deepdive.md)
* Product: **xamarin**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by CeciAc** [comment]
Hello, @hrafil
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hrafil
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hrafil

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/cs-cz/xamarin/android/get-started/hello-android/hello-android-deepdive?pivots=windows. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
